### PR TITLE
fix: Changed -NaN to NaN 

### PR DESCRIPTION
**Pull request by IndranilKhedkar**
Close https://github.com/denoland/deno-docs/issues/76 
Update key_space.mdx

### CODE REVIEW

**Comment by hashrock** [comment]
I think NaN shouldn't appear twice because it's about key ordering

**Comment by kt3k** [comment]
cc @losfair Is NaN bigger than `Infinity`, or less than `-Infinity`?

**Comment by IndranilKhedkar** [comment]
As per Lodash `sortBy` function `NaN` is bigger than `Infinity`
image

**Comment by kt3k** [comment]
I also checked with the below script:
```js
const kv = await Deno.openKv(":memory:");
await kv.set([Infinity], 1);
await kv.set([NaN], 1);
await kv.set([-Infinity], 1);
for await (const res of kv.list({ prefix: [] })) {
  console.log(res);
}
```
It prints the below:
```
{ key: [ -Infinity ], value: 1, versionstamp: "00000000000000030000" }
{ key: [ Infinity ], value: 1, versionstamp: "00000000000000010000" }
{ key: [ NaN ], value: 1, versionstamp: "00000000000000020000" }
```
So it looks like `Infinity < NaN` in Deno KV

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
